[toolchain]
anchor_version = "1.1.2"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_level_1_token_starter = "56ak38Zzznbe9cV3pkGBgSYWjLPRT74Aa9za4Bry1ATx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
